name: Build & Deploy (Anachrony)

on:
  workflow_dispatch:

concurrency:
  group: deploy-anachrony
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: code/2025-11-05/anachrony

    steps:
      - name: Get latest code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"
          cache: "yarn"
          cache-dependency-path: code/2025-11-05/anachrony/yarn.lock

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Build the project
        run: yarn build

      - name: List output files
        run: find dist/ -print

      - name: Copy files to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          server-dir: /sites/lab.tekh.studio/anachrony/
          local-dir: code/2025-11-05/anachrony/dist/
